{
    "0": "Plasmaschwertwurf",
    "2": "Plasmaschwertwurf",
    "5": "Plasmaschwertwurf",
    "6": "EINFACH ALLE ABKNALLEN",
    "9": "EINFACH ALLE ABKNALLEN",
    "10": "Antimaterie Sturm",
    "12": "Antimaterie Sturm",
    "14": "Keine Kiste kommt nie allein",
    "18": "Angriff der Mystery Decals",
    "21": "Angriff der Mystery Decals",
    "22": "Mettwurst !Blutwuurst Strudäl!",
    "24": "Mettwurst Sign !Wurst-chan macht derbe Dinge!",
    "26": "Mettwurst Sign !Blaues Datum des Arrg!",
    "28": "Mettwurst Sign !3-fache Laberrung der Wurst Göttin!",
    "29": "Unendliche Verdauungsstörung",
    "30": "Mettwurst Sign !Oger Verwiuiirung!",
    "32": "Mettwurst Sign !Noch mehr verwirrte Oger!",
    "34": "Mettwurst Sign !Die Wurst in die Hand nehmen!",
    "36": "Blaues abklatschen",
    "37": "Sich in der Langeweile verlieren",
    "38": "Mettwurst Sign !Apokalyptscher Gott Wuurst!",
    "42": "Angriff der Bewertungskarten",
    "44": "Angriff der Bewertungskarten",
    "46": "Sterne des alten Bewertungssystems",
    "48": "Sterne des alten Bewertungssystems",
    "50": "Flut der künstlichen Aromen",
    "52": "Flut der künstlichen Aromen",
    "54": "Fanpost von Gameboy Irgendwas",
    "58": "Nervig sein",
    "60": "Nervig sein",
    "62": "Na hast du spaß (; ?",
    "64": "Na hast du spaß (; ?",
    "66": "Matze Nervung !Ich bin noch da!",
    "69": "Matze Nervung !Ich bin noch da!",
    "70": "Lukas Sign !Geschmolzene Welten!",
    "74": "Fuck Apollo",
    "76": "Apollo Hägh Theory",
    "78": "Entgegenkommen des Lichtes",
    "82": "Quarks Bowlingkugeln",
    "86": "Versammelte Hinrichtung",
    "88": "Versammelte Hinrichtung",
    "90": "Verzweifelt scheinender Stern",
    "94": "Corrupted !Sonne der Gottlosen!",
    "98": "BLEIB STEHN EY! D:<",
    "101": "BLEIB STEHN EY! D:<",
    "102": "Corrupted !Freundlichkeit und Zuversicht!",
    "104": "Corrupted !Freundlichkeit und Zuversicht!",
    "106": "Super Schimmelung !Fickende Lämmer!",
    "107": "Might and Magic Blaster Bug",
    "108": "Blue Lady Show",
    "109": "Pi in the Sky",
    "110": "Zu viele Torpedos",
    "111": "Raikos Rachsüchtige Geister",
    "112": "Simple Danmaku for Cornering a Trapped Matze",
    "113": "ARMAGEDON!!!",
    "114": "Die Erde ist ja heiß Herr Lustig",
    "115": "Echt viele Blitze",
    "116": "Pures Danmaku zum Töten einer Person",
    "117": "Der wahre Satz des Pythagoras",
    "118": "Erstes und letztes Danmaku",
	"119": "Blue Lady Show",
	"120": "Keine Ahnung was passiert ist",
	"125": "Echt große Dinger",
	"126": "Ganz viel Musik",
    "45": "Angriff der Bewertungskarten"
}